config_version = "1.0.0"

[ environments.dev ] 
host = "___host_name___"
username = "___user_name___"
password = "__password__"    # We keep password here for demo purposes - it is strongly recommended 
							 # to define user password via environment variable
extraction.databases = [ "dev_admin" ]
git_branch = "master"
writer.target_dir="./teradata-code"
tagging_rules = [ "{{env}}%" ]

environments.dev.tagging_variables.env = "dev"
