name = "{{env}}_app_user"
kind = "user"
owner = "{{env}}_env"
perm_space = "0"
spool_space = "20000000"
temp_space = "10000000"
default_database = "{{env}}_wrk"
account = "prod_account"
password = "<REDACTED>"
comment = "Application user for prod environment with role-based access"
only_in = [
    "prod",
]
