name = "{{env}}_env"
kind = "user"
owner = "demo_user"
perm_space = "0"
spool_space = "100000000"
temp_space = "50000000"
default_database = "{{env}}_env"
account = "prod_account"
password = "<REDACTED>"
comment = "Root user for prod environment - contains all environment databases"
